export interface ItineraryItem {
  id: number;
  time: string;
  activity: string;
  icon: string;
  location: string;
  address: string;
  mapUrl: string;
  caption: string;
  day: "friday" | "saturday" | "sunday";
  image?: string; // Venue logo/photo for the card
  characterImage?: string; // Custom illustration (Jo-Yo themed)
  websiteUrl?: string;
}

export const itinerary: ItineraryItem[] = [
  // Friday, February 13
  {
    id: 2,
    time: "9:00 AM",
    activity: "Spa Nordik",
    icon: "🧖‍♀️",
    location: "Chelsea, QC",
    address: "16 Chemin Nordik, Chelsea, QC J9B 2P7",
    mapUrl: "https://maps.google.com/?q=16+Chemin+Nordik,+Chelsea,+QC+J9B+2P7",
    caption: "Relaxation time for my Baby Dragon 🐉",
    day: "friday",
    image: "/images/activities/spa-nordik-logo.png",
    characterImage: "/images/activities/spa-nordik.png",
    websiteUrl: "https://chelsea.lenordik.com/",
  },
  {
    id: 3,
    time: "5:00 PM",
    activity: "Home - Get Ready",
    icon: "👗",
    location: "Home",
    address: "",
    mapUrl: "",
    caption: "Time to get pretty (you already are, Lovey)",
    day: "friday",
    characterImage: "/images/activities/getready-character.png",
  },
  {
    id: 4,
    time: "6:45 PM",
    activity: "Beckta Restaurant",
    icon: "🍽️",
    location: "Ottawa",
    address: "150 Elgin Street, Ottawa, ON K2P 1L4",
    mapUrl: "https://maps.google.com/?q=150+Elgin+Street,+Ottawa,+ON+K2P+1L4",
    caption: "Fine dining for my fine Labubu",
    day: "friday",
    image: "/images/activities/beckta-logo.png",
    characterImage: "/images/activities/beckta-character.png",
    websiteUrl: "https://beckta.com/",
  },
  {
    id: 5,
    time: "9:00 PM",
    activity: "Mask + Movie",
    icon: "🎭",
    location: "Home",
    address: "",
    mapUrl: "",
    caption: "Cozy night with my Snack Queen 👑",
    day: "friday",
    image: "/images/activities/netflix-logo.png",
    characterImage: "/images/activities/movie-friday.png",
  },

  // Saturday, February 14 - Valentine's Day
  {
    id: 6,
    time: "Morning",
    activity: "Roses + Breakfast in Bed",
    icon: "🌹",
    location: "Home",
    address: "",
    mapUrl: "",
    caption: "Good morning, my Valentine! 💕",
    day: "saturday",
    characterImage: "/images/activities/breakfast-character.png",
  },
  {
    id: 7,
    time: "9:00 AM",
    activity: "Camp Fortune Skiing",
    icon: "⛷️",
    location: "Chelsea, QC",
    address: "300 Chemin Dunlop, Chelsea, QC J9B 2N3",
    mapUrl: "https://maps.google.com/?q=300+Chemin+Dunlop,+Chelsea,+QC+J9B+2N3",
    caption: "Adventure time with my Baby Dragon! 🏔️",
    day: "saturday",
    image: "/images/activities/camp-fortune-logo.jpg",
    characterImage: "/images/activities/camp-fortune.png",
    websiteUrl: "https://campfortune.com/",
  },
  {
    id: 8,
    time: "3:00 PM",
    activity: "Home - Shower Together",
    icon: "🚿",
    location: "Home",
    address: "",
    mapUrl: "",
    caption: "Getting ready for our dinner dates 😏",
    day: "saturday",
    characterImage: "/images/activities/shower-character.png",
  },
  {
    id: 9,
    time: "5:00 PM",
    activity: "Erling's Variety",
    icon: "🍴",
    location: "Ottawa",
    address: "225 Strathcona Ave, Ottawa, ON K1S 1X7",
    mapUrl: "https://maps.google.com/?q=225+Strathcona+Ave,+Ottawa,+ON+K1S+1X7",
    caption: "Dinner #1 for the Hungry Hippo 🦛",
    day: "saturday",
    image: "/images/activities/erlings-logo.png",
    characterImage: "/images/activities/erlings-character.png",
    websiteUrl: "https://www.erlingsvariety.com/",
  },
  {
    id: 10,
    time: "9:30 PM",
    activity: "Rosebowl Steakhouse",
    icon: "🥩",
    location: "Ottawa",
    address: "228 Preston Street, Ottawa, ON K1R 7R4",
    mapUrl: "https://maps.google.com/?q=228+Preston+Street,+Ottawa,+ON+K1R+7R4",
    caption: "Dinner #2 - because one isn't enough for my Menu Destroyer 💀",
    day: "saturday",
    image: "/images/activities/rosebowl-logo.png",
    characterImage: "/images/activities/rosebowl-character.png",
    websiteUrl: "https://www.rosebowlsteakhouse.com/",
  },
  {
    id: 11,
    time: "Late Night",
    activity: "Mask + Movie",
    icon: "🎬",
    location: "Home",
    address: "",
    mapUrl: "",
    caption: "Valentine's night cuddles with Nan Nan 🥰",
    day: "saturday",
    image: "/images/activities/netflix-logo.png",
    characterImage: "/images/activities/movie-saturday.png",
  },

  // Sunday, February 16
  {
    id: 12,
    time: "9:00 AM",
    activity: "Almonte Road Trip",
    icon: "🏕️",
    location: "Almonte, ON",
    address: "Mill Street, Almonte, ON",
    mapUrl: "https://maps.google.com/?q=Mill+Street,+Almonte,+ON",
    caption: "Exploring a cute town together!",
    day: "sunday",
    image: "/images/activities/almonte.jpg",
    websiteUrl: "https://almonte.com/",
  },
  {
    id: 13,
    time: "12:00 PM",
    activity: "Costco",
    icon: "💕",
    location: "Our Love Place",
    address: "",
    mapUrl: "",
    caption: "Where bulk buying meets true love 🛒❤️",
    day: "sunday",
    image: "/images/activities/costco-logo.png",
    characterImage: "/images/activities/costco-character.png",
  },
  {
    id: 14,
    time: "1:00 PM",
    activity: "IKEA",
    icon: "🛋️",
    location: "Ottawa",
    address: "",
    mapUrl: "",
    caption: "Building our future together (literally) 🔧",
    day: "sunday",
    image: "/images/activities/ikea-logo.png",
    characterImage: "/images/activities/ikea-character.png",
  },
  {
    id: 15,
    time: "5:30 PM",
    activity: "Restaurant E18hteen",
    icon: "🦞",
    location: "Ottawa",
    address: "18 York Street, Ottawa, ON K1N 5T5",
    mapUrl: "https://maps.google.com/?q=18+York+Street,+Ottawa,+ON+K1N+5T5",
    caption: "Grand finale dinner for my Little Dumpling 🥟",
    day: "sunday",
    image: "/images/activities/e18hteen.jpg",
    characterImage: "/images/activities/e18hteen-character.png",
    websiteUrl: "https://www.restaurant18.com/",
  },
  {
    id: 16,
    time: "Evening",
    activity: "Mask + Movie",
    icon: "🎭",
    location: "Home",
    address: "",
    mapUrl: "",
    caption: "Perfect ending to a perfect weekend 💖",
    day: "sunday",
    image: "/images/activities/netflix-logo.png",
    characterImage: "/images/activities/movie-sunday.png",
  },
];

export const dayLabels = {
  friday: "Friday 13",
  saturday: "Saturday 14 💝",
  sunday: "Sunday 16",
};

export const nicknames = [
  "Nan Nan",
  "Labubu",
  "Baby Dragon",
  "Lovey",
  "Snack Queen 👑",
  "My Little Dumpling 🥟",
  "Hungry Hippo 🦛",
  "The Menu Destroyer 💀",
  "Miss 'This Is My Favorite!'",
  "Buffet Boss",
  "Snackasaurus Rex 🦖",
  "Professional Food Appreciator",
];
